---
- name: Download consul
  get_url:
    url: https://releases.hashicorp.com/consul/1.5.3/consul_1.5.3_linux_amd64.zip
    dest: /tmp/consul.zip
    mode: '0440'

- name: Extract consul.zip into /usr/local/bin
  unarchive:
    src: /tmp/consul.zip
    dest: /usr/local/bin
    remote_src: yes

- name: place consul configuration file.
  copy:
    src: files/consul-client.json
    dest: /usr/local/etc/consul.json
    owner: root
    group: root
    mode: '0644'
