---
# ansible-playtbook k8s-node-setup.yml
- name: main
  hosts: "*"
  tasks:
    - name: install base software
      yum:
        name: "{{ packages }}"
        state: latest
      vars:
        packages:
        - open-vm-tools
        - yum-utils
        - device-mapper-persistent-data
        - lvm2
