---
- name: install docker-ce yum repo
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

- name: install docker-ce using yum
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - docker-ce.x86_64 3:19.03.2-3.el7
    - docker-ce-cli
    - containerd.io

- name: Start service docker, if not started
  service:
    name: docker
    state: started
    enabled: yes
