--- 
- name: place resolv.conf.good.
  copy:
    src: files/resolv.conf.good
    dest: /etc/resolv.conf.good
    owner: root
    group: root
    mode: '0640'
- name: Update and lock /etc/resolv.conf 
  command: chattr -i /etc/resolv.conf;cat /etc/resolv.conf.good >/etc/resolv.conf;chattr +i /etc/resolv.conf

