---
- name: Create /linux-tools
  file:
    path: /linux-tools
    state: directory

- name: Add /linux-tools Mount
  lineinfile:
    path: /etc/fstab
    regexp: '^synology:/volume1/linux-tools'
    line: synology:/volume1/linux-tools /linux-tools nfs rw 0 2

- name: Create /Movies
  file:
    path: /mnt/Movies
    state: directory

- name: Add /Movies Mount
  lineinfile:
    path: /etc/fstab
    regexp: '^synology:/volume1/Movies'
    line: synology:/volume1/Movies /mnt/Movies nfs rw 0 2

- name: Create /TV-Shows
  file:
    path: /mnt/TV-Shows
    state: directory

- name: Add /mnt/TV-Shows Mount
  lineinfile:
    path: /etc/fstab
    regexp: '^synology:/volume1/TV-Shows /mnt/TV-Shows nfs rw 0 2'
    line: synology:/volume1/TV-Shows /mnt/TV-Shows nfs rw 0 2

- name: Create /mnt/TV-Shows1
  file:
    path: /mnt/TV-Shows1
    state: directory

- name: Add /TV-Shows1 Mount
  lineinfile:
    path: /etc/fstab
    regexp: '^synology:/volume1/TV-Shows1 /mnt/TV-Shows1 nfs rw 0 2'
    line: synology:/volume1/TV-Shows1 /mnt/TV-Shows1 nfs rw 0 2

- name: Create /mnt/sabnzb
  file:
    path: /mnt/sabnzb
    state: directory

- name: Add /sabnzb Mount
  lineinfile:
    path: /etc/fstab
    regexp: '^synology:/volume1/sabnzb'
    line: synology:/volume1/sabnzb /mnt/sabnzb nfs rw 0 2

- name: Mounting all filesystems.
  command: mount -a
