---
- name: Base packages install
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - nfs-common
    - git
    - curl
    - apt-transport-https
#    - ansible
#    - molecule
    - python3-pip
    - libssl-dev
    - cockpit

# - name: Remove packages
#   yum:
#     name: "{{ packages }}"
#     state:  absent
#   vars:
#     packages:
#     - gcc

- name: Enable cockpit
  service:
    name: cockpit
    state: started
    enabled: yes
