---
- name: Base packages install
  apt:
    name: "{{ packages }}"
  vars:
    packages:
    - nfs-common
    - git
    - ansible
    - molecule
    - python3-pip
    - libssl-dev

# - name: Remove packages
#   yum:
#     name: "{{ packages }}"
#     state:  absent
#   vars:
#     packages:
#     - gcc
