---
- name: Base packages install
  yum:
    name: "{{ packages }}"
  vars:
    packages:
    - java-1.8.0-openjdk-devel

# import a key from a elasticsearch
- rpm_key:
    state: present
    key: https://artifacts.elastic.co/GPG-KEY-elasticsearch

# Place repo file.
---
- name: place elasticsearch repo file
  copy:
    src: files/elasticsearch.repo
    dest: /etc/yum.repos.d/elasticsearch.repo
    owner: root
    group: root
    mode: '0644'
