- name: Ensure SELinux is set to permissive mode.
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: Disable selinux on systems.
  command: setenforce 0
  ignore_errors: yes

- name: Stop firewalld
  service:
    name: firewalld
    state: stopped
    enabled: no

- import_tasks: install-packages.yaml
