- import_tasks: install-packages.yaml

- name: Ensure SELinux is set to permissive mode.
  lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: SELINUX=disabled

- name: Disable selinux on systems.
  command: setenforce 0

- name: Start service elasticsearch, if not started
  service:
    name: firewalld
    state: stopped
    enabled: no
